### ISSUE TITLE
With the new android gradle plugin 3.x it's no longer needed to specify buildToolsVersion

### ISSUE THREAD

**Issue by scdc** [rakutentech/android-buildconfig#6]
have you planed to remove buildToolsVersion settings soon or find a way to apply different android config for recent projects? 

Just for information:
Warning:The specified Android SDK Build Tools version (26.0.1) is ignored, as it is below the minimum supported version (26.0.2) for Android Gradle Plugin 3.0.1.
Android SDK Build Tools 26.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.1'" from your build.gradle file, **as each version of the Android Gradle Plugin now has a default version of the build tools**.

**Comment by NemoOudeis** [comment]
which files do you mean? the `versions.gradle` or `android/library.gradle`/`android/application.gradle`?
If you use the versions in `versions.gradle` for both plugin and app/lib config the versions should be consistent. But it sounds like you use `master` app/lib config with AGP 3, is that correct?

Currently we have not migrated our SDKs to AGP 3, which is why `master` still agp `2.3.3` - if you use AGP 3 you can use the `agp3` branch, which will be coexisting parallel to master for a bit.

**Comment by scdc** [comment]
I was talking about android/library.gradle and android/application.gradle files. And yes I'm using the master branch with AGP 3.

I was not aware about the AGP 3 branch I will switch to it, thank you for your quick answer :)

**Comment by jcayzac** [comment]
Also for NDK it’s not needed to pass in the sdk as a macro anymore

**Comment by NemoOudeis** [comment]
@jcayzac i don't quite get what you mean by "pass in the sdk as a macro" - could you elaborate please?
@scdc Sorry for the late reply. You are right that the build tools are obsolete and don't need to be manually synched by the config after migrating to agp3. 
So I'll remove it from the agp3 branch.

**Comment by jcayzac** [comment]
I mean that defining the `ANDROID_PLATFORM` (min sdk), `ANDROID_TOOLCHAIN` (clang) & `ANDROID_STL` (gnustl_static) C processor macros when configuring Cmake is not required anymore.

**Comment by NemoOudeis** [comment]
I see, good to know.
We are not using the NDK currently and have no configuration for it in the shared [android config](https://github.com/rakutentech/android-buildconfig/blob/master/android/android.gradle) so i'll close this issue for now.
🤘🏼
